version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    command: uvicorn podcast_app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./podcast_app/outputs:/app/podcast_app/outputs
      - ./podcast_app/music:/app/podcast_app/music
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: .
    command: celery -A podcast_app.tasks worker --loglevel=info --pool=solo
    env_file:
      - .env
    volumes:
      - ./podcast_app/outputs:/app/podcast_app/outputs
      - ./podcast_app/outputs:/app/podcast_app/music
    depends_on:
      redis:
        condition: service_healthy



